project_id = "mybwxaszvtwiwtxigibw"

[functions.beyondpresence-transcript]
verify_jwt = true

[functions.conversation]
verify_jwt = true

[functions.elevenlabs-agent]
verify_jwt = true

[functions.generate-transcript]
verify_jwt = true