// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mybwxaszvtwiwtxigibw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15Ynd4YXN6dnR3aXd0eGlnaWJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3Mzk3OTAsImV4cCI6MjA3NDMxNTc5MH0.ZE6DAeaWIi8gqPAaA1r7ku4_K1TjlM6cF7dQfwR5J90";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});